"""add assurances table

Revision ID: 2842f5d4d2af
Revises: 1384cbd4b1dd
Create Date: 2026-10-05 07:49:22.641893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2842f5d4d2af'
down_revision: Union[str, Sequence[str], None] = '1384cbd4b1dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assurances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('object_version', sa.String(length=50), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('assurance_type', sa.String(length=100), nullable=False),
    sa.Column('ai_system_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assurances')
    # ### end Alembic commands ###
