"""add evidence table

Revision ID: 37de21943654
Revises: 30b0c9922419
Create Date: 2026-10-04 23:25:19.488509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37de21943654'
down_revision: Union[str, Sequence[str], None] = '30b0c9922419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_title', sa.String(length=500), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('object_version', sa.String(length=50), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('evidence_description', sa.Text(), nullable=True),
    sa.Column('evidence_type', sa.String(length=200), nullable=True),
    sa.Column('format', sa.String(length=100), nullable=True),
    sa.Column('ai_system_id', sa.String(length=128), nullable=True),
    sa.Column('lifecycle_stage', sa.String(length=100), nullable=True),
    sa.Column('control_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessment_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    # ### end Alembic commands ###
