"""add classifications table

Revision ID: 6b84603ef3ca
Revises: 5357f19e34d2
Create Date: 2026-10-05 01:19:46.160352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b84603ef3ca'
down_revision: Union[str, Sequence[str], None] = '5357f19e34d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ai_system_id', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('object_version', sa.String(length=50), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assessment_type', sa.String(length=100), nullable=False),
    sa.Column('subject', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessment_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applicable_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_considerations', sa.String(length=5000), nullable=True),
    sa.Column('evaluation_scope', sa.String(length=5000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_system_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classifications')
    # ### end Alembic commands ###
