"""add evaluations table

Revision ID: b006b66efbfe
Revises: 6b84603ef3ca
Create Date: 2026-10-05 01:34:07.903321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b006b66efbfe'
down_revision: Union[str, Sequence[str], None] = '6b84603ef3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ai_system_id', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('object_version', sa.String(length=50), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assessment_type', sa.String(length=100), nullable=False),
    sa.Column('subject', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessment_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluation_purpose', sa.String(length=5000), nullable=True),
    sa.Column('governance_context', sa.String(length=5000), nullable=True),
    sa.Column('evaluation_scope', sa.String(length=5000), nullable=True),
    sa.Column('evaluation_trigger', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_system_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluations')
    # ### end Alembic commands ###
