"""add controls

Revision ID: d62dfe53fda8
Revises: 753c98a9b20a
Create Date: 2026-10-05 22:53:24.165502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd62dfe53fda8'
down_revision: Union[str, Sequence[str], None] = '753c98a9b20a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ai_system_id', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('object_version', sa.String(length=50), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('control_name', sa.String(length=256), nullable=False),
    sa.Column('control_objective', sa.Text(), nullable=False),
    sa.Column('control_owner', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('control_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('controls')
    # ### end Alembic commands ###
